### ISSUE TITLE
CHORE: Update Discord Join Link

### ISSUE THREAD

**Issue by LayerDynamics** [Sahomey-Technologies/sahomedb#10]
discord link is dead, have some questions for you guys but have no way to join
<img width="643" alt="Screenshot 2024-08-12 at 9 55 09 PM" src="https://github.com/user-attachments/assets/0064fede-9ded-4867-8e36-f5576ce1d182">

**Comment by chinosam** [comment]
Will update and i'll let you know

**Comment by obaraelijah** [comment]
Hi, i updated the link you can join the server

**Comment by LayerDynamics** [comment]
thank you!
